# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
units: config/units.tsv

resources:
    ctat_path: "/path/to/ctat_reference"


params:
    trim_galore:
        arguments: "--paired -q 20 "


docker:
    ctat:
        container: "trinityctat/ctat_mutations:3.3.1"
        path: "/usr/local/src/ctat-mutations/ctat_mutations"


paths:
    workdir: "/path/to/workdir"
    results_dir: "/path/to/results_dir"
    tmp_dir: "/path/to/tmp_dir"